version: "3.9"

services:
  web:
    image: "nginx:latest"
    ports:
      - "8080:80"
      - "443:443"
    volumes:
        - ./www:/var/www/html
        - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx
    links:
        - php
    networks:
        - frontend
  php:
    image: "php:fpm"
    volumes:
        - ./www:/var/www/html
        - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    links:
        - redis
    networks:
        - frontend
        - backend
  redis:
    image: "redis:latest"
    networks:
        - backend
networks:
  frontend:
    driver: bridge
    ipam:
       driver: default
       config:
         - subnet: 172.16.0.0/24
           gateway: 172.16.0.1
  backend:
    driver: bridge
