version: "3.9"

services:
  web:
    image: "nginx:latest"
    volumes:
        - ./site:/var/www/html
    ports:
      - "80:80"
      - "443:443"
  php:
    image: "php:7.4-fpm"
  redis:
    image: "redis:latest"
